name: 'Main pipeline'

on:
  push:
    branches:
      - main

jobs:
  service-1-deployment:
    uses: ./.github/workflows/service-deployment.yaml
    with:
      service-name: service-1
      version: v1.0
      customer-1: true
      customer-2: true

  service-2-deployment:
    uses: ./.github/workflows/service-deployment.yaml
    with:
      service-name: service-2
      version: v3.0
      customer-1: true
      customer-2: false
